spring.application.name=GestionCursos
server.port=813
spring.datasource.url=mysql://avnadmin:AVNS_yu0F1SIHxKFobZy1qCZ@mysql-graphixstory-duocuc-d2a7.h.aivencloud.com:23330/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect